name: Run build
on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  build-agent:
    name: "Build agent for ${{ matrix.os-name }}"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        include:
          - os: ubuntu-latest
            os-name: Linux
            rust-target: x86_64-unknown-linux-gnu

          - os: windows-latest
            os-name: Windows
            rust-target: x86_64-pc-windows-msvc

      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install protoc
        uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build agent
        run: |
          cargo build --target ${{ matrix.rust-target }} --package dragon-claw-agent --bin dragon-claw-agent

      - name: Upload agent executable
        uses: actions/upload-artifact@v3
        with:
          name: dragon-claw-agent
          path: |
            target/${{ matrix.rust-target }}/debug/dragon-claw-agent
            target/${{ matrix.rust-target }}/debug/dragon-claw-agent.exe

  build-android-app:
    name: "Build android app"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install protoc
        uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install Pub packages
        run: flutter pub get
        working-directory: app

      - name: Install Dart protobuf plugin
        run: flutter pub global activate protoc_plugin
        working-directory: app

      - name: Generate protobufs
        run: ./gen-protobufs.sh
        working-directory: app

      - name: Build APK
        run: flutter build apk --debug
        working-directory: app

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: dragon-claw-app
          path: app/build/app/outputs/flutter-apk/app-debug.apk
